language: go
script: true
sudo: false

go:
  - 1.7
  - tip

before_install:
  - go get github.com/golang/lint/golint

install:
  - go get
  - go build

script:
  - go test ./...
  - $HOME/gopath/bin/golint ./...
